In [1]:
import numpy as np
from numpy import unravel_index

a = np.array([[1,2,3],[9,5,6],[4,7,6]])
b = np.array([[1,1,2],[4,5,6]])

print(a)
print(a[1:-1, 1:-1])
unravel_index(a.argmax(), a.shape)

[[1 2 3]
 [9 5 6]
 [4 7 6]]
[[5]]


(1, 0)

In [2]:
2//2

1

In [5]:
w = np.random.randint(5, size=(2, 3, 2, 4))
print(w)
print('-'*50)
print(np.transpose(w, (1,0,2,3)))
print('-'*50)
print(np.mean(w,axis=0))

[[[[0 0 1 4]
   [3 2 2 4]]

  [[3 3 1 2]
   [1 4 1 4]]

  [[2 1 3 4]
   [0 0 1 0]]]


 [[[1 2 4 1]
   [2 1 4 4]]

  [[1 3 2 0]
   [0 1 0 1]]

  [[3 3 3 4]
   [2 1 4 3]]]]
--------------------------------------------------
[[[[0 0 1 4]
   [3 2 2 4]]

  [[1 2 4 1]
   [2 1 4 4]]]


 [[[3 3 1 2]
   [1 4 1 4]]

  [[1 3 2 0]
   [0 1 0 1]]]


 [[[2 1 3 4]
   [0 0 1 0]]

  [[3 3 3 4]
   [2 1 4 3]]]]
--------------------------------------------------
[[[ 0.5  1.   2.5  2.5]
  [ 2.5  1.5  3.   4. ]]

 [[ 2.   3.   1.5  1. ]
  [ 0.5  2.5  0.5  2.5]]

 [[ 2.5  2.   3.   4. ]
  [ 1.   0.5  2.5  1.5]]]


In [38]:
np.pad(a, mode='constant', pad_width=[(0,0),(2,2),(2,2)])

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  1.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [40]:
int(1.5)

1